print(10*5)
print(10**2)
print(15/10)
print(15//10)
print(15%10)
print(10%15)
print(10%10)
print(0%10)
print(10/15) #should not repeat
rate = int(input("Enter the current exchange rate for Euro to USD"))
rate = float(rate)
amount = int(input("Enter the amount of currency to exchange"))
amount = float(amount)
total = int(rate*amount)
result = int(total-3)
print(result)